### ISSUE TITLE
IOS is not compiling with undefined symbol errors

### ISSUE THREAD

**Issue by jpudysz** [przelewy24/p24-mobile-lib-react-native-example#6]
I wasn't able to compile it inside my project. I tried with your example with the same result. I'm receiving multiple `Undefined sumbol` errors.

Steps to reproduce:
```
1. install p24-mobile-lib-react-native-example
2. npm/yarn install
```

Result:
```
Undefined symbol: _OBJC_CLASS_$_PKPaymentAuthorizationResult

Undefined symbol: _OBJC_CLASS_$_PKPaymentAuthorizationViewController

Undefined symbol: _OBJC_CLASS_$_PKPaymentRequest

Undefined symbol: _OBJC_CLASS_$_PKPaymentSummaryItem

Undefined symbol: _PKPaymentNetworkMasterCard

Undefined symbol: _PKPaymentNetworkVisa
```

Expected result:
```
Lib has been compiled
```

**Comment by przelewy24mobile** [comment]
The problem is caused by missing framework PassKit - you should add mentioned framework to Your Projects -> General -> Linked Frameworks. If problem still will be occured, don't hesitate to ask us.

**Comment by jpudysz** [comment]
Thanks! I will give it a try. Please update README.md for iOS project it would be nice to know such things :)
